### ISSUE TITLE
RunTests.sh deleted

### ISSUE THREAD

**Issue by sdat2** [adcirc/adcirc-testsuite#17]
Hi, 

The README.md still says to run `./RunTests.sh` but that shell file has been removed as far as I can see. Is the readme out of date or was the deletion accidental? 

Perhaps it should direct users to the new python script  `test_runner.py` instead. I think the new command is something like: 

```bash
python test_runner/test_runner.py --bin /path/to/adcirc/work/ --tolerance 0.00001 --test-yaml /path/to/adcirc-testsuite/test_list.yaml --test-root /path/to/adcirc-testsuite/ --all
```
(requirments `pyyaml`, `tqdm`, `xarray`, `netCDF4`)

**Comment by zcobell** [comment]
Thanks for pointing this out. The `README.md` file has been updated.
