### ISSUE TITLE
Error for adcprep while output fort.63.nc

### ISSUE THREAD

**Issue by liujuantang** [adcirc/adcirc-testsuite#9]
Dear ADCIRC Developers,

I ran into adcprep error using adc55-cg-dev when I tried to output fort.63.nc. Error message attached at the end.
My grid is about 800K with 4 river discharges in fort.20. Before I only output fort.61 for validation testing and it had no problem. 

The adc55-cg-dev  version of adcprep can work only with either one of (1) or (2) but not (1)+(2)
(1) river discharges (without fort.63.nc)
(2) output fort.63.nc (with no river discharges )

William helped me fix the issue by removing all the ibtype  = 20 boundaries and kept only the ibtype = 22 ones (rivers) from the fort.14. Doing this operation means that I only have a total of 18 nodes on the boundary for the river inputs and it seems to work.

Liujuan Rachel Tang
NOAA/NOS/OCS/CMMB

Error message:
free(): invalid next size (normal): 0x00000000081f1170 ***  
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7ff11d8a4299]
./adcprep(for_dealloc_allocatable+0x210)[0x6a3d80]
./adcprep[0x553945]
./adcprep[0x496742]
./adcprep[0x42c123]
./adcprep[0x42afca]
./adcprep[0x40daa2]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff11d845555]
./adcprep[0x40d9a9]
======= Memory map: ========
00400000-00822000 r-xp 00000000 909:56882 144118268590833297             /mnt/lfs4/NOS/vdatum/Liujuan.Tang/adcirc/adcirc-cg-55-dev/work/adcprep
00a21000-00a23000 r--p 00421000 909:56882 144118268590833297             /mnt/lfs4/NOS/vdatum/Liujuan.Tang/adcirc/adcirc-cg-55-dev/work/adcprep
00a23000-00ae2000 rw-p 00423000 909:56882 144118268590833297             /mnt/lfs4/NOS/vdatum/Liujuan.Tang/adcirc/adcirc-cg-55-dev/work/adcprep
00ae2000-00e4b000 rw-p 00000000 00:00 0
0267d000-0b91a000 rw-p 00000000 00:00 0                                  [heap]
7fec78000000-7fec78021000 rw-p 00000000 00:00 0
7fec78021000-7fec7c000000 ---p 00000000 00:00 0
7fec7f20f000-7ff11ad18000 rw-p 00000000 00:00 0
7ff11b03b000-7ff11b161000 r-xp 00000000 00:16 27852745                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifcore.so.5
7ff11b161000-7ff11b361000 ---p 00126000 00:16 27852745                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifcore.so.5
7ff11b361000-7ff11b366000 rw-p 00126000 00:16 27852745                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifcore.so.5
7ff11b366000-7ff11b36d000 rw-p 00000000 00:00 0
7ff11b36d000-7ff11b392000 r-xp 00000000 00:16 27852747                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifport.so.5
7ff11b392000-7ff11b592000 ---p 00025000 00:16 27852747                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifport.so.5
7ff11b592000-7ff11b594000 rw-p 00025000 00:16 27852747                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libifport.so.5
7ff11b594000-7ff11b59a000 rw-p 00000000 00:00 0
7ff11b59a000-7ff11b5f3000 r-xp 00000000 00:16 27852782                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libintlc.so.5
7ff11b5f3000-7ff11b7f2000 ---p 00059000 00:16 27852782                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libintlc.so.5
7ff11b7f2000-7ff11b7f4000 rw-p 00058000 00:16 27852782                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libintlc.so.5
7ff11b7f4000-7ff11b7f5000 rw-p 00000000 00:00 0
7ff11b7f5000-7ff11c491000 r-xp 00000000 00:16 27852805                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libsvml.so
7ff11c491000-7ff11c690000 ---p 00c9c000 00:16 27852805                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libsvml.so
7ff11c690000-7ff11c6c8000 rw-p 00c9b000 00:16 27852805                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libsvml.so
7ff11c6c8000-7ff11c942000 r-xp 00000000 00:16 27852808                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libimf.so
7ff11c942000-7ff11cb41000 ---p 0027a000 00:16 27852808                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libimf.so
7ff11cb41000-7ff11cb83000 rw-p 00279000 00:16 27852808                   /apps/intel/composer_xe_2015.3.187/compiler/lib/intel64/libimf.so
7ff11cb83000-7ff11cb8d000 r-xp 00000000 00:16 21766814                   /apps/szip/2.1/lib/libsz.so.2.0.0
7ff11cb8d000-7ff11cd8d000 ---p 0000a000 00:16 21766814                   /apps/szip/2.1/lib/libsz.so.2.0.0
7ff11cd8d000-7ff11cd8e000 rw-p 0000a000 00:16 21766814                   /apps/szip/2.1/lib/libsz.so.2.0.0
7ff11cd8e000-7ff11cd96000 rw-p 00000000 00:00 0
7ff11cd96000-7ff11cd9d000 r-xp 00000000 00:16 69225369                   /usr/lib64/librt-2.17.so
7ff11cd9d000-7ff11cf9c000 ---p 00007000 00:16 69225369                   /usr/lib64/librt-2.17.so
7ff11cf9c000-7ff11cf9d000 r--p 00006000 00:16 69225369                   /usr/lib64/librt-2.17.so
7ff11cf9d000-7ff11cf9e000 rw-p 00007000 00:16 69225369                   /usr/lib64/librt-2.17.so
7ff11cf9e000-7ff11cfb3000 r-xp 00000000 00:16 69226656                   /usr/lib64/libz.so.1.2.7
7ff11cfb3000-7ff11d1b2000 ---p 00015000 00:16 69226656                   /usr/lib64/libz.so.1.2.7
7ff11d1b2000-7ff11d1b3000 r--p 00014000 00:16 69226656                   /usr/lib64/libz.so.1.2.7
7ff11d1b3000-7ff11d1b4000 rw-p 00015000 00:16 69226656                   /usr/lib64/libz.so.1.2.7
7ff11d1b4000-7ff11d1f7000 r-xp 00000000 00:16 69226111                   /usr/lib64/libjpeg.so.62.1.0
7ff11d1f7000-7ff11d3f7000 ---p 00043000 00:16 69226111                   /usr/lib64/libjpeg.so.62.1.0
7ff11d3f7000-7ff11d3f8000 r--p 00043000 00:16 69226111                   /usr/lib64/libjpeg.so.62.1.0
7ff11d3f8000-7ff11d3f9000 rw-p 00044000 00:16 69226111                   /usr/lib64/libjpeg.so.62.1.0
7ff11d3f9000-7ff11d409000 rw-p 00000000 00:00 0
7ff11d409000-7ff11d40b000 r-xp 00000000 00:16 69224673                   /usr/lib64/libdl-2.17.so
7ff11d40b000-7ff11d60b000 ---p 00002000 00:16 69224673                   /usr/lib64/libdl-2.17.so
7ff11d60b000-7ff11d60c000 r--p 00002000 00:16 69224673                   /usr/lib64/libdl-2.17.so
7ff11d60c000-7ff11d60d000 rw-p 00003000 00:16 69224673                   /usr/lib64/libdl-2.17.so
7ff11d60d000-7ff11d622000 r-xp 00000000 00:16 69212740                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7ff11d622000-7ff11d821000 ---p 00015000 00:16 69212740                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7ff11d821000-7ff11d822000 r--p 00014000 00:16 69212740                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7ff11d822000-7ff11d823000 rw-p 00015000 00:16 69212740                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7ff11d823000-7ff11d9e7000 r-xp 00000000 00:16 69224224                   /usr/lib64/libc-2.17.so
7ff11d9e7000-7ff11dbe6000 ---p 001c4000 00:16 69224224                   /usr/lib64/libc-2.17.so
7ff11dbe6000-7ff11dbea000 r--p 001c3000 00:16 69224224                   /usr/lib64/libc-2.17.so
7ff11dbea000-7ff11dbec000 rw-p 001c7000 00:16 69224224                   /usr/lib64/libc-2.17.so
7ff11dbec000-7ff11dbf1000 rw-p 00000000 00:00 0
7ff11dbf1000-7ff11dc08000 r-xp 00000000 00:16 69225219                   /usr/lib64/libpthread-2.17.so
7ff11dc08000-7ff11de07000 ---p 00017000 00:16 69225219                   /usr/lib64/libpthread-2.17.so
7ff11de07000-7ff11de08000 r--p 00016000 00:16 69225219                   /usr/lib64/libpthread-2.17.so
7ff11de08000-7ff11de09000 rw-p 00017000 00:16 69225219                   /usr/lib64/libpthread-2.17.so
7ff11de09000-7ff11de0d000 rw-p 00000000 00:00 0
7ff11de0d000-7ff11df0e000 r-xp 00000000 00:16 69224705                   /usr/lib64/libm-2.17.so
7ff11df0e000-7ff11e10d000 ---p 00101000 00:16 69224705                   /usr/lib64/libm-2.17.so
7ff11e10d000-7ff11e10e000 r--p 00100000 00:16 69224705                   /usr/lib64/libm-2.17.so
7ff11e10e000-7ff11e10f000 rw-p 00101000 00:16 69224705                   /usr/lib64/libm-2.17.so
7ff11e10f000-7ff11e489000 r-xp 00000000 00:16 69021934                   /apps/hdf5/1.8.9-intel/lib/libhdf5.so.7.0.3
7ff11e489000-7ff11e688000 ---p 0037a000 00:16 69021934                   /apps/hdf5/1.8.9-intel/lib/libhdf5.so.7.0.3
7ff11e688000-7ff11e697000 rw-p 00379000 00:16 69021934                   /apps/hdf5/1.8.9-intel/lib/libhdf5.so.7.0.3
7ff11e697000-7ff11e698000 rw-p 00000000 00:00 0
7ff11e698000-7ff11e6bb000 r-xp 00000000 00:16 69021927                   /apps/hdf5/1.8.9-intel/lib/libhdf5_hl.so.7.0.3
7ff11e6bb000-7ff11e8ba000 ---p 00023000 00:16 69021927                   /apps/hdf5/1.8.9-intel/lib/libhdf5_hl.so.7.0.3
7ff11e8ba000-7ff11e8bc000 rw-p 00022000 00:16 69021927                   /apps/hdf5/1.8.9-intel/lib/libhdf5_hl.so.7.0.3
7ff11e8bc000-7ff11e8cd000 rw-p 00000000 00:00 0
7ff11e8cd000-7ff11e914000 r-xp 00000000 00:16 69021921                   /apps/hdf5/1.8.9-intel/lib/libhdf5_fortran.so.7.0.3
7ff11e914000-7ff11eb14000 ---p 00047000 00:16 69021921                   /apps/hdf5/1.8.9-intel/lib/libhdf5_fortran.so.7.0.3
7ff11eb14000-7ff11eb17000 rw-p 00047000 00:16 69021921                   /apps/hdf5/1.8.9-intel/lib/libhdf5_fortran.so.7.0.3
7ff11eb17000-7ff11ebbb000 r-xp 00000000 00:16 23341030                   /apps/netcdf/4.2.1.1-intel/lib/libnetcdff.so.5.3.1
7ff11ebbb000-7ff11edbb000 ---p 000a4000 00:16 23341030                   /apps/netcdf/4.2.1.1-intel/lib/libnetcdff.so.5.3.1
7ff11edbb000-7ff11edbd000 rw-p 000a4000 00:16 23341030                   /apps/netcdf/4.2.1.1-intel/lib/libnetcdff.so.5.3.1
7ff11edbd000-7ff11ef7d000 rw-p 00000000 00:00 0
7ff11ef7d000-7ff11f0e8000 r-xp 00000000 00:16 23341034                   /apps/netcdf/4.2.1.1-intel/lib/libnetcdf.so.7.2.0
7ff11f0e8000-7ff11f2e8000 ---p 0016b000 00:16 23341034                   /apps/netcdf/4.2.1.1-intel/lib/libnetcdf.so.7.2.0
7ff11f2e8000-7ff11f33d000 rw-p 0016b000 00:16 23341034                   /apps/netcdf/4.2.1.1-intel/lib/libnetcdf.so.7.2.0
7ff11f33d000-7ff11f36d000 rw-p 00000000 00:00 0
7ff11f36d000-7ff11f38f000 r-xp 00000000 00:16 69207019                   /usr/lib64/ld-2.17.so
7ff11f565000-7ff11f56e000 rw-p 00000000 00:00 0
7ff11f580000-7ff11f581000 rw-p 00000000 00:00 0
7ff11f581000-7ff11f58b000 r--p 00000000 00:16 28580806                   /apps/intel/compilers_and_libraries_2019.5.281/linux/compiler/lib/intel64_lin/locale/en_US/ifcore_msg.cat
7ff11f58b000-7ff11f58e000 rw-p 00000000 00:00 0
7ff11f58e000-7ff11f58f000 r--p 00021000 00:16 69207019                   /usr/lib64/ld-2.17.so
7ff11f58f000-7ff11f590000 rw-p 00022000 00:16 69207019                   /usr/lib64/ld-2.17.so
7ff11f590000-7ff11f591000 rw-p 00000000 00:00 0
7fff8f2e1000-7fff8f41a000 rw-p 00000000 00:00 0                          [stack]
7fff8f500000-7fff8f502000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
./run_prep_adcprep_slurm_20200529.sh: line 40: 22030 Aborted                 ./adcprep < decomp2.in > decomp2.out

**Comment by zcobell** [comment]
Closing as stale (@liujuantang  - if you still have this issue, please open in the main ADCIRC repository and we'll address there)
